#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


module RDL::Type

class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 188)

def initialize()
  @yydebug = true
end

...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    79,    43,    21,    39,    19,    20,    92,    22,    91,    15,
    14,    16,   103,   -26,   133,    32,    17,   104,    18,    41,
    95,    96,    41,    89,    90,     7,    40,    89,    90,    40,
    21,   140,    19,    20,   123,    22,   141,    54,    14,    16,
    94,    93,    11,   142,    17,   143,    61,    97,     5,     6,
    55,    57,    56,    58,    59,    60,    21,   123,    19,    20,
     8,    22,     7,    54,    14,    16,     7,    37,    11,    66,
    17,    67,    61,    65,    68,    69,    55,    57,    56,    58,
    59,    60,    21,    70,    19,    20,    72,    22,    30,    33,
    14,    16,    75,    72,    11,    80,    17,    81,    18,    82,
    29,    34,    13,    32,    35,    21,    83,    19,    20,    84,
    22,    30,    33,    14,    16,    86,    87,    11,    88,    17,
   -12,    18,    98,    29,    34,    13,    32,    35,    47,    99,
    45,    46,   100,   101,    47,    43,    45,    46,    48,   107,
     7,    43,   112,   113,    48,    21,   117,    19,    20,    50,
    22,     7,    15,    14,    16,    50,   121,    11,   122,    17,
   125,    18,     7,   127,    21,    13,    19,    20,   129,    22,
   130,    15,    14,    16,   nil,   nil,    11,   nil,    17,   nil,
    18,   nil,   nil,    21,    13,    19,    20,   nil,    22,   nil,
    15,    14,    16,   nil,   nil,    11,   nil,    17,   nil,    18,
   nil,   nil,    21,    13,    19,    20,   nil,    22,   nil,    15,
    14,    16,   nil,   nil,    11,   nil,    17,   nil,    18,   nil,
   nil,    21,    13,    19,    20,   nil,    22,   nil,    15,    14,
    16,   nil,   nil,    11,   nil,    17,   nil,    18,   nil,   nil,
    21,    13,    19,    20,   nil,    22,   nil,    15,    14,    16,
   nil,   nil,    11,   nil,    17,   nil,    18,   nil,   nil,   110,
    13,    21,   nil,    19,    20,   nil,    22,   nil,    15,    14,
    16,   nil,   nil,    11,   nil,    17,   nil,    18,   nil,   nil,
    21,    13,    19,    20,   nil,    22,   nil,    15,    14,    16,
   nil,   nil,    11,   nil,    17,   nil,    18,   nil,   nil,    21,
    13,    19,    20,   nil,    22,   nil,    15,    14,    16,    21,
   nil,    19,    20,    17,    22,    18,    15,    14,    16,    13,
   nil,   nil,   nil,    17,   nil,    18,   nil,   nil,    21,    13,
    19,    20,   nil,    22,   nil,    15,    14,    16,    21,   nil,
    19,    20,    17,    22,    18,    15,    14,    16,    13,   nil,
   nil,   nil,    17,   nil,    18,   nil,   nil,    21,    13,    19,
    20,   nil,    22,   nil,    15,    14,    16,   nil,   nil,    11,
   nil,    17,   nil,    18,   nil,   nil,    21,    13,    19,    20,
   nil,    22,   nil,    15,    14,    16,   nil,   nil,    11,   nil,
    17,   nil,    18,   nil,   nil,    21,    13,    19,    20,   nil,
    22,   nil,    15,    14,    16,   nil,   nil,    11,   nil,    17,
   nil,    18,   nil,   132,    21,    13,    19,    20,   nil,    22,
   nil,    15,    14,    16,    21,   nil,    19,    20,    17,    22,
    18,    15,    14,    16,    13,   nil,   nil,   nil,    17,   nil,
    18,   nil,   nil,    21,    13,    19,    20,   nil,    22,   nil,
    15,    14,    16,   137,   nil,    11,   nil,    17,   nil,    18,
   nil,   nil,   139,    13,   nil,   nil,   138,    57,    56,    58,
    59,    60,    21,   nil,    19,    20,   nil,    22,   nil,    15,
    14,    16,   nil,   nil,   nil,   nil,    17,   nil,    18 ]

racc_action_check = [
    42,    70,    55,    12,    55,    55,    58,    55,    58,    55,
    55,    55,    67,    97,   126,    70,    55,    67,    55,    42,
    60,    60,    12,   138,   138,   127,    42,    55,    55,    12,
    61,   131,    61,    61,    97,    61,   134,    61,    61,    61,
    59,    59,    61,   139,    61,   140,    61,    61,     0,     0,
    61,    61,    61,    61,    61,    61,    18,   142,    18,    18,
     1,    18,     0,    18,    18,    18,     6,     8,    18,    21,
    18,    24,    18,    18,    27,    28,    18,    18,    18,    18,
    18,    18,     7,    31,     7,     7,    33,     7,     7,     7,
     7,     7,    38,    43,     7,    45,     7,    46,     7,    47,
     7,     7,     7,     7,     7,    68,    48,    68,    68,    49,
    68,    68,    68,    68,    68,    51,    52,    68,    53,    68,
    54,    68,    62,    68,    68,    68,    68,    68,    17,    63,
    17,    17,    64,    66,    84,    17,    84,    84,    17,    69,
    17,    84,    77,    78,    84,    98,    82,    98,    98,    17,
    98,    88,    98,    98,    98,    84,    91,    98,    95,    98,
   102,    98,   103,   104,    34,    98,    34,    34,   117,    34,
   120,    34,    34,    34,   nil,   nil,    34,   nil,    34,   nil,
    34,   nil,   nil,    35,    34,    35,    35,   nil,    35,   nil,
    35,    35,    35,   nil,   nil,    35,   nil,    35,   nil,    35,
   nil,   nil,   110,    35,   110,   110,   nil,   110,   nil,   110,
   110,   110,   nil,   nil,   110,   nil,   110,   nil,   110,   nil,
   nil,    41,   110,    41,    41,   nil,    41,   nil,    41,    41,
    41,   nil,   nil,    41,   nil,    41,   nil,    41,   nil,   nil,
    72,    41,    72,    72,   nil,    72,   nil,    72,    72,    72,
   nil,   nil,    72,   nil,    72,   nil,    72,   nil,   nil,    72,
    72,     5,   nil,     5,     5,   nil,     5,   nil,     5,     5,
     5,   nil,   nil,     5,   nil,     5,   nil,     5,   nil,   nil,
    11,     5,    11,    11,   nil,    11,   nil,    11,    11,    11,
   nil,   nil,    11,   nil,    11,   nil,    11,   nil,   nil,    79,
    11,    79,    79,   nil,    79,   nil,    79,    79,    79,    80,
   nil,    80,    80,    79,    80,    79,    80,    80,    80,    79,
   nil,   nil,   nil,    80,   nil,    80,   nil,   nil,    81,    80,
    81,    81,   nil,    81,   nil,    81,    81,    81,    83,   nil,
    83,    83,    81,    83,    81,    83,    83,    83,    81,   nil,
   nil,   nil,    83,   nil,    83,   nil,   nil,    32,    83,    32,
    32,   nil,    32,   nil,    32,    32,    32,   nil,   nil,    32,
   nil,    32,   nil,    32,   nil,   nil,    50,    32,    50,    50,
   nil,    50,   nil,    50,    50,    50,   nil,   nil,    50,   nil,
    50,   nil,    50,   nil,   nil,   125,    50,   125,   125,   nil,
   125,   nil,   125,   125,   125,   nil,   nil,   125,   nil,   125,
   nil,   125,   nil,   125,   129,   125,   129,   129,   nil,   129,
   nil,   129,   129,   129,    39,   nil,    39,    39,   129,    39,
   129,    39,    39,    39,   129,   nil,   nil,   nil,    39,   nil,
    39,   nil,   nil,    40,    39,    40,    40,   nil,    40,   nil,
    40,    40,    40,   130,   nil,    40,   nil,    40,   nil,    40,
   nil,   nil,   130,    40,   nil,   nil,   130,   130,   130,   130,
   130,   130,    13,   nil,    13,    13,   nil,    13,   nil,    13,
    13,    13,   nil,   nil,   nil,   nil,    13,   nil,    13 ]

racc_action_pointer = [
    43,    60,   nil,   nil,   nil,   254,    47,    75,    67,   nil,
   nil,   273,    -1,   465,   nil,   nil,   nil,   121,    49,   nil,
   nil,    55,   nil,   nil,    51,   nil,   nil,    72,    61,   nil,
   nil,    81,   350,    75,   157,   176,   nil,   nil,    72,   417,
   436,   214,    -4,    82,   nil,    87,    89,    85,    98,   107,
   369,    93,    94,   107,   109,    -5,   nil,   nil,   -24,     9,
   -12,    23,   120,   105,   108,   nil,   111,    -9,    98,   121,
   -13,   nil,   233,   nil,   nil,   nil,   nil,   111,   119,   292,
   302,   321,   124,   331,   127,   nil,   nil,   nil,   132,   nil,
   nil,   125,   nil,   nil,   nil,   126,   nil,     2,   138,   nil,
   nil,   nil,   157,   143,   142,   nil,   nil,   nil,   nil,   nil,
   195,   nil,   nil,   nil,   nil,   nil,   nil,   160,   nil,   nil,
   168,   nil,   nil,   nil,   nil,   388,    -8,     6,   nil,   407,
   439,    17,   nil,   nil,    14,   nil,   nil,   nil,    -9,    19,
    27,   nil,    25,   nil ]

racc_action_default = [
   -84,   -84,    -1,    -2,    -3,   -84,   -84,   -30,   -84,    -4,
   -53,   -84,   -66,   -84,   -70,   -71,   -72,   -57,   -84,   -80,
   -81,   -84,   -83,    -5,   -84,   -31,   -32,   -33,   -36,   -39,
   -40,   -41,   -84,   -71,   -84,   -84,   -47,   144,   -84,   -84,
   -84,   -84,   -68,   -84,   -58,   -84,   -84,   -84,   -84,   -63,
   -84,   -84,   -84,   -84,   -71,   -13,   -14,   -15,   -16,   -18,
   -84,   -84,   -55,   -84,   -84,   -78,   -84,   -50,   -84,   -38,
   -84,   -42,   -84,   -45,   -46,   -54,   -67,   -84,   -84,   -84,
   -84,   -84,   -84,   -84,   -57,   -64,   -75,   -79,   -84,   -21,
   -29,   -17,   -24,   -19,   -25,   -20,   -28,   -78,   -84,   -76,
   -77,   -82,   -84,   -84,   -84,   -34,   -35,   -37,   -43,   -44,
   -84,   -49,   -73,   -74,   -69,   -59,   -60,   -84,   -62,   -65,
   -10,   -23,   -22,   -27,   -56,   -84,   -84,   -84,   -48,   -84,
   -84,    -6,    -9,   -51,   -84,   -61,   -11,   -12,   -13,   -84,
    -7,   -52,   -26,    -8 ]

racc_goto_table = [
     2,     9,    52,    36,    44,    25,    23,    38,    76,    26,
    24,    42,   102,   109,   136,    77,    78,    51,     4,     3,
     1,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    71,   nil,
    73,    74,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    85,   nil,   114,   115,
   116,   nil,   118,    42,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    36,   nil,   105,   nil,   111,   119,
   106,    44,   108,   124,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   120,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   135,   nil,
   nil,   nil,   nil,   126,   nil,   nil,   128,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   131,   nil,   nil,   nil,   nil,   nil,   134 ]

racc_goto_check = [
     2,     5,    19,     5,    14,    10,     2,     5,    16,    11,
     6,    20,     7,    15,     8,    17,    17,     2,     4,     3,
     1,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,
     5,     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,    16,    16,
    16,   nil,    16,    20,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     5,   nil,    10,   nil,     5,    19,
    11,    14,    11,    17,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,   nil,
   nil,   nil,   nil,     2,   nil,   nil,     5,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     5,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,    20,     0,    19,    18,    -4,     3,   -55,  -116,   nil,
    -2,     2,   nil,   nil,   -13,   -59,   -31,   -25,   nil,   -15,
    -2 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    62,   nil,   nil,    64,    53,
   nil,   nil,    27,    28,    31,   nil,    10,    63,    49,   nil,
    12 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 36, :_reduce_1,
  1, 36, :_reduce_2,
  1, 36, :_reduce_3,
  2, 38, :_reduce_4,
  2, 39, :_reduce_5,
  6, 37, :_reduce_6,
  7, 37, :_reduce_7,
  8, 37, :_reduce_8,
  6, 37, :_reduce_9,
  3, 43, :_reduce_10,
  5, 43, :_reduce_11,
  1, 44, :_reduce_12,
  1, 44, :_reduce_13,
  1, 44, :_reduce_14,
  1, 44, :_reduce_15,
  1, 44, :_reduce_16,
  2, 44, :_reduce_17,
  1, 44, :_reduce_18,
  2, 44, :_reduce_19,
  2, 44, :_reduce_20,
  2, 44, :_reduce_21,
  3, 44, :_reduce_22,
  3, 44, :_reduce_23,
  2, 44, :_reduce_24,
  2, 44, :_reduce_25,
  2, 44, :_reduce_26,
  3, 44, :_reduce_27,
  2, 44, :_reduce_28,
  2, 44, :_reduce_29,
  0, 41, :_reduce_30,
  1, 41, :_reduce_31,
  1, 41, :_reduce_32,
  1, 45, :_reduce_33,
  3, 45, :_reduce_34,
  3, 45, :_reduce_35,
  1, 47, :_reduce_36,
  3, 47, :_reduce_37,
  2, 47, :_reduce_38,
  1, 47, :_reduce_39,
  1, 47, :_reduce_40,
  1, 46, :_reduce_41,
  2, 46, :_reduce_42,
  3, 46, :_reduce_43,
  3, 49, :_reduce_44,
  2, 48, :_reduce_45,
  2, 48, :_reduce_46,
  1, 48, :_reduce_47,
  2, 50, :_reduce_48,
  1, 50, :_reduce_49,
  0, 42, :_reduce_50,
  3, 42, :_reduce_51,
  4, 42, :_reduce_52,
  1, 40, :_reduce_53,
  3, 40, :_reduce_54,
  1, 52, :_reduce_55,
  3, 52, :_reduce_56,
  0, 53, :_reduce_none,
  1, 53, :_reduce_58,
  3, 53, :_reduce_59,
  3, 53, :_reduce_60,
  5, 53, :_reduce_61,
  3, 53, :_reduce_62,
  1, 54, :_reduce_63,
  2, 54, :_reduce_64,
  3, 54, :_reduce_65,
  1, 51, :_reduce_66,
  3, 51, :_reduce_67,
  2, 51, :_reduce_68,
  4, 51, :_reduce_69,
  1, 55, :_reduce_70,
  1, 55, :_reduce_71,
  1, 55, :_reduce_72,
  4, 55, :_reduce_73,
  4, 55, :_reduce_74,
  3, 55, :_reduce_75,
  3, 55, :_reduce_76,
  3, 55, :_reduce_77,
  2, 55, :_reduce_78,
  3, 55, :_reduce_79,
  1, 55, :_reduce_80,
  1, 55, :_reduce_81,
  3, 55, :_reduce_82,
  1, 55, :_reduce_83 ]

racc_reduce_n = 84

racc_shift_n = 144

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :RARROW => 3,
  :OR => 4,
  :HASH_TYPE => 5,
  :HASH_QUERY => 6,
  :CONST_BEGIN => 7,
  :RASSOC => 8,
  :FIXNUM => 9,
  :FLOAT => 10,
  :COLON => 11,
  :DOT => 12,
  :DOTS => 13,
  :ID => 14,
  :SYMBOL => 15,
  :SPECIAL_ID => 16,
  :STRING => 17,
  :PREDICATE => 18,
  :LPAREN => 19,
  :RPAREN => 20,
  :LBRACE => 21,
  :RBRACE => 22,
  :LBRACKET => 23,
  :RBRACKET => 24,
  :COMP => 25,
  :QUERY => 26,
  :BANG => 27,
  :STARSTAR => 28,
  :STAR => 29,
  :LESS => 30,
  :GREATER => 31,
  :EQUAL => 32,
  :TILDE => 33,
  :EOF => 34 }

racc_nt_base = 35

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "RARROW",
  "OR",
  "HASH_TYPE",
  "HASH_QUERY",
  "CONST_BEGIN",
  "RASSOC",
  "FIXNUM",
  "FLOAT",
  "COLON",
  "DOT",
  "DOTS",
  "ID",
  "SYMBOL",
  "SPECIAL_ID",
  "STRING",
  "PREDICATE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COMP",
  "QUERY",
  "BANG",
  "STARSTAR",
  "STAR",
  "LESS",
  "GREATER",
  "EQUAL",
  "TILDE",
  "EOF",
  "$start",
  "entry",
  "method_type",
  "bare_type",
  "query_type",
  "type_expr",
  "arg_list",
  "block",
  "method_sig_list",
  "method_name",
  "nonempty_arg_list",
  "named_arg_list",
  "arg",
  "base_arg",
  "named_arg",
  "base_arg_query_only",
  "union_type",
  "type_expr_comma_list",
  "hash_expr",
  "hash_expr_comma_list",
  "single_type" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_1(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 20)
  def _reduce_3(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_4(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 26)
  def _reduce_5(val, _values, result)
     result = RDL::Type::MethodType.new val[1].args, val[1].block, val[1].ret 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 30)
  def _reduce_6(val, _values, result)
            result = RDL::Type::MethodType.new val[1], val[3], val[5]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 33)
  def _reduce_7(val, _values, result)
            result = RDL::Type::MethodType.new val[1], val[3], RDL::Type::AnnotatedArgType.new(val[6], val[5])
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_8(val, _values, result)
            result = RDL::Type::MethodType.new val[1], val[3], RDL::Type::DependentArgType.new(val[6], val[5], val[7])
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_9(val, _values, result)
         	result = RDL::Type::MethodType.new(val[1], val[3], RDL::Type::ComputedType.new(val[5]))
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 43)
  def _reduce_10(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 44)
  def _reduce_11(val, _values, result)
     result = [val[0], val[2]] + val[4] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 47)
  def _reduce_12(val, _values, result)
     result = val[0].to_sym 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 48)
  def _reduce_13(val, _values, result)
     result = :! 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 49)
  def _reduce_14(val, _values, result)
     result = :* 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 50)
  def _reduce_15(val, _values, result)
     result = :** 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 51)
  def _reduce_16(val, _values, result)
     result = :< 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 52)
  def _reduce_17(val, _values, result)
     result = :<= 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 53)
  def _reduce_18(val, _values, result)
     result = :> 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 54)
  def _reduce_19(val, _values, result)
     result = :>= 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 55)
  def _reduce_20(val, _values, result)
     result = :== 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 56)
  def _reduce_21(val, _values, result)
     result = :!= 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 57)
  def _reduce_22(val, _values, result)
     result = :=== 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 58)
  def _reduce_23(val, _values, result)
     result = :<=> 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 59)
  def _reduce_24(val, _values, result)
     result = :<< 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_25(val, _values, result)
     result = :>> 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 61)
  def _reduce_26(val, _values, result)
     result = :[] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 62)
  def _reduce_27(val, _values, result)
     result = :[]= 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 63)
  def _reduce_28(val, _values, result)
     result = :=~ 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_29(val, _values, result)
     result = :!~ 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 67)
  def _reduce_30(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_31(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 70)
  def _reduce_32(val, _values, result)
          result = [RDL::Type::FiniteHashType.new(Hash[*val[0][0]], val[0][1])]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 73)
  def _reduce_33(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_34(val, _values, result)
     result = val[2].unshift val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 75)
  def _reduce_35(val, _values, result)
     # named arg list must come last
      result = [val[0], RDL::Type::FiniteHashType.new(Hash[*val[2][0]], val[2][1])]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 79)
  def _reduce_36(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 80)
  def _reduce_37(val, _values, result)
     result = RDL::Type::DependentArgType.new(val[1], val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_38(val, _values, result)
     result = RDL::Type::AnnotatedArgType.new(val[1], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 82)
  def _reduce_39(val, _values, result)
     result = RDL::Type::ComputedType.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 83)
  def _reduce_40(val, _values, result)
     result = RDL::Type::DotsQuery.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_41(val, _values, result)
     result = [val[0], nil] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_42(val, _values, result)
     result = [[], val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 87)
  def _reduce_43(val, _values, result)
     result = [val[0] + val[2][0], val[2][1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 89)
  def _reduce_44(val, _values, result)
     result = [val[0].to_sym, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 92)
  def _reduce_45(val, _values, result)
     result = RDL::Type::OptionalType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_46(val, _values, result)
     result = RDL::Type::VarargType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 94)
  def _reduce_47(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 96)
  def _reduce_48(val, _values, result)
     result = RDL::Type::OptionalType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 97)
  def _reduce_49(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_50(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 101)
  def _reduce_51(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 102)
  def _reduce_52(val, _values, result)
     result = RDL::Type::OptionalType.new val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 105)
  def _reduce_53(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 106)
  def _reduce_54(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 109)
  def _reduce_55(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 110)
  def _reduce_56(val, _values, result)
     result = [val[0]] + val[2] 
    result
  end
.,.,

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.racc', 113)
  def _reduce_58(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 114)
  def _reduce_59(val, _values, result)
     result = [val[0].to_i, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 115)
  def _reduce_60(val, _values, result)
     result = [val[0].to_f, val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 117)
  def _reduce_61(val, _values, result)
        result = [Kernel.const_get(val[0]), val[2]]
  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 119)
  def _reduce_62(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 122)
  def _reduce_63(val, _values, result)
     result = [val[0], nil] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 123)
  def _reduce_64(val, _values, result)
     result = [[], val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 124)
  def _reduce_65(val, _values, result)
     result = [val[0] + val[2][0], val[2][1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 127)
  def _reduce_66(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 128)
  def _reduce_67(val, _values, result)
     result = RDL::Type::UnionType.new val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 129)
  def _reduce_68(val, _values, result)
     result = RDL::Type::NonNullType.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 130)
  def _reduce_69(val, _values, result)
     result = RDL::Type::UnionType.new(RDL::Type::NonNullType.new(val[1]), val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 133)
  def _reduce_70(val, _values, result)
     result = RDL::Type::SingletonType.new(val[0].to_sym) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 135)
  def _reduce_71(val, _values, result)
          if val[0] == 'nil' then
        result = RDL::Globals.types[:nil]
      elsif val[0] == 'true' then
        result = RDL::Globals.types[:true]
      elsif val[0] == 'false'
        result = RDL::Globals.types[:false]
      elsif val[0] =~ /^[a-z_]+\w*\'?/ then
        result = RDL::Type::VarType.new(val[0].to_sym)
      else
        result = RDL::Type::NominalType.new val[0]
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 148)
  def _reduce_72(val, _values, result)
          if RDL::Globals.special_types.has_key? val[0] then
        result = RDL::Globals.special_types[val[0]]
      else
        fail "Unexpected special type identifier #{val[0]}"
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 155)
  def _reduce_73(val, _values, result)
          result = RDL::Type::GenericType.new(val[0], *val[2])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 158)
  def _reduce_74(val, _values, result)
          result = RDL::Type::AstNode.new(:SELECT, RDL::Type::SingletonType.new(*val[2]))
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 160)
  def _reduce_75(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 162)
  def _reduce_76(val, _values, result)
          result = RDL::Type::TupleType.new(*val[1])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 165)
  def _reduce_77(val, _values, result)
          result = RDL::Type::StructuralType.new(Hash[*val[1]])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 168)
  def _reduce_78(val, _values, result)
          result = RDL::Type::TupleType.new
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 171)
  def _reduce_79(val, _values, result)
          result = RDL::Type::FiniteHashType.new(Hash[*val[1][0]], val[1][1])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 173)
  def _reduce_80(val, _values, result)
     result = RDL::Type::SingletonType.new(val[0].to_i) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 174)
  def _reduce_81(val, _values, result)
     result = RDL::Type::SingletonType.new(val[0].to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 176)
  def _reduce_82(val, _values, result)
          result =  RDL::Type::SingletonType.new(Kernel.const_get(val[1]))
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 180)
  def _reduce_83(val, _values, result)
     result = RDL::Type::WildQuery.new 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser


end
